spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  session:
    store-type: none

  redis:
    host: 36.152.17.61
    port: 6379



security:
  basic:
    enabled: false

server:
  port: 8080




mao:
  security:
     browser:
       loginPage: /index.html
       #loginType: REDIRECT
       loginType: JSON


     code:
        image:
          width: 67
          height: 23
          lenght: 4
          expireIn: 60
          url: /user/list,/user/info/*