spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  session:
    store-type: REDIS
    #store-type: REDIS

  redis:
    host: 36.152.17.61
    port: 6379



security:
  basic:
    enabled: false

  oauth2:
    client:
      clientId: maohua
      clientScret: 123456


server:
  port: 8080
  session:
    timeout: 1800




mao:
  security:
     browser:
       loginPage: /index.html
       #loginType: REDIRECT
       loginType: JSON
     oauth2:
       storeType: jwt



     code:
        image:
          width: 67
          height: 23
          lenght: 4
          expireIn: 60
          url: /user/list,/user/info/*

